-- Drop all tables first to avoid conflicts
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS access_logs;
DROP TABLE IF EXISTS activity_logs;
DROP TABLE IF EXISTS admin_users;
DROP TABLE IF EXISTS announcements;
DROP TABLE IF EXISTS announcement_media;
DROP TABLE IF EXISTS announcement_types;
DROP TABLE IF EXISTS applications;
DROP TABLE IF EXISTS application_documents;
DROP TABLE IF EXISTS application_types;
DROP TABLE IF EXISTS archives;
DROP TABLE IF EXISTS archives_expanded;
DROP TABLE IF EXISTS barangays;
DROP TABLE IF EXISTS benefits;
DROP TABLE IF EXISTS benefit_claims;
DROP TABLE IF EXISTS benefit_history;
DROP TABLE IF EXISTS benefit_transactions;
DROP TABLE IF EXISTS benefit_types;
DROP TABLE IF EXISTS branches;
DROP TABLE IF EXISTS branch_barangays;
DROP TABLE IF EXISTS cache;
DROP TABLE IF EXISTS cache_locks;
DROP TABLE IF EXISTS complaints;
DROP TABLE IF EXISTS complaint_categories;
DROP TABLE IF EXISTS complaint_documents;
DROP TABLE IF EXISTS complaint_statuses;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS document_types;
DROP TABLE IF EXISTS educational_attainment;
DROP TABLE IF EXISTS event_participants;
DROP TABLE IF EXISTS failed_jobs;
DROP TABLE IF EXISTS family_members;
DROP TABLE IF EXISTS genders;
DROP TABLE IF EXISTS id_printing_queue;
DROP TABLE IF EXISTS id_statuses;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS job_batches;
DROP TABLE IF EXISTS migrations;
DROP TABLE IF EXISTS mobility_levels;
DROP TABLE IF EXISTS password_reset_tokens;
DROP TABLE IF EXISTS personal_access_tokens;
DROP TABLE IF EXISTS pre_registrations;
DROP TABLE IF EXISTS registration_statuses;
DROP TABLE IF EXISTS senior_accounts;
DROP TABLE IF EXISTS senior_citizens;
DROP TABLE IF EXISTS senior_citizens_with_benefits;
DROP TABLE IF EXISTS senior_eligible_benefits;
DROP TABLE IF EXISTS senior_ids;
DROP TABLE IF EXISTS senior_target_sectors;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS socioeconomic_statuses;
DROP TABLE IF EXISTS target_sectors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS user_permissions;
DROP TABLE IF EXISTS user_roles;

SET FOREIGN_KEY_CHECKS = 1;

-- Tables dropped. Now you can import scis_clean.sql
