<?php

namespace App\Services;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Drawing;
use Symfony\Component\HttpFoundation\StreamedResponse;

class ExcelExportService
{
    private Spreadsheet $spreadsheet;
    private $sheet;
    private int $dataStartRow;

    // Colors
    private const RED = 'C0392B';
    private const GREEN = '27AE60';
    private const YELLOW_LIGHT = 'FFF9C4';
    private const RED_DARK = '922B21';
    private const WHITE = 'FFFFFF';
    private const BLACK = '000000';
    private const GRAY_LIGHT = 'F5F5F5';

    //Create a new Excel export with letterhead
    public function create(string $subtitle, array $headers, array $data, string $generatedBy = 'System'): self
    {
        $this->spreadsheet = new Spreadsheet();
        $this->sheet = $this->spreadsheet->getActiveSheet();

        $colCount = count($headers);
        $lastCol = $this->colLetter($colCount);

        $this->addLetterhead($subtitle, $lastCol, $colCount, $generatedBy);
        $this->addHeaders($headers, $lastCol);
        $this->addData($data, $colCount);
        $this->autoSizeColumns($colCount);

        return $this;
    }

    //Add the letterhead: logo + government headers + metadata
    private function addLetterhead(string $subtitle, string $lastCol, int $colCount, string $generatedBy): void
    {
        // Set row heights for letterhead
        $this->sheet->getRowDimension(1)->setRowHeight(14);
        $this->sheet->getRowDimension(2)->setRowHeight(16);
        $this->sheet->getRowDimension(3)->setRowHeight(16);
        $this->sheet->getRowDimension(4)->setRowHeight(20);
        $this->sheet->getRowDimension(5)->setRowHeight(6);

        // Add logo — floats over the merged header area
        $this->sheet->mergeCells('A1:A4');

        $logoPath = resource_path('images/osca_logo.jpg');
        if (file_exists($logoPath)) {
            $drawing = new Drawing();
            $drawing->setName('OSCA Logo');
            $drawing->setPath($logoPath);
            $drawing->setHeight(70);
            $drawing->setCoordinates('A1');
            $drawing->setOffsetX(5);
            $drawing->setOffsetY(2);
            $drawing->setWorksheet($this->sheet);
        }

        $mergeEnd = $lastCol;

        // Row 1: REPUBLIC OF THE PHILIPPINES (merge A1 is already merged for logo, text in B)
        $this->sheet->mergeCells("B1:{$mergeEnd}1");
        $this->sheet->setCellValue('B1', 'REPUBLIC OF THE PHILIPPINES');
        $this->styleCell('B1', 10, false, self::BLACK, Alignment::HORIZONTAL_CENTER);

        // Row 2: CITY GOVERNMENT OF ZAMBOANGA
        $this->sheet->mergeCells("B2:{$mergeEnd}2");
        $this->sheet->setCellValue('B2', 'CITY GOVERNMENT OF ZAMBOANGA');
        $this->styleCell('B2', 11, false, self::BLACK, Alignment::HORIZONTAL_CENTER);

        // Row 3: SENIOR CITIZENS INFORMATION SYSTEM (SCIS) — bold
        $this->sheet->mergeCells("B3:{$mergeEnd}3");
        $this->sheet->setCellValue('B3', 'SENIOR CITIZENS INFORMATION SYSTEM (SCIS)');
        $this->styleCell('B3', 13, true, self::RED_DARK, Alignment::HORIZONTAL_CENTER);

        // Row 4: Subtitle (report type)
        $this->sheet->mergeCells("B4:{$mergeEnd}4");
        $this->sheet->setCellValue('B4', strtoupper($subtitle));
        $this->styleCell('B4', 11, true, self::BLACK, Alignment::HORIZONTAL_CENTER);

        // Row 5: Empty separator
        $this->sheet->mergeCells("A5:{$mergeEnd}5");

        // Row 6: Empty
        $this->sheet->mergeCells("A6:{$mergeEnd}6");

        // Row 7: Report metadata
        $this->sheet->setCellValue('A7', 'Report Generated:');
        $this->styleCell('A7', 10, true, self::BLACK);

        $phDate = new \DateTime('now', new \DateTimeZone('Asia/Manila'));
        $this->sheet->setCellValue('B7', $phDate->format('F d, Y h:i A'));
        $this->styleCell('B7', 10, false, self::BLACK);

        // Generated by — align right side
        $midCol = $this->colLetter(max(1, $colCount - 2));
        $this->sheet->setCellValue("{$midCol}7", 'Generated by:');
        $this->styleCell("{$midCol}7", 10, true, self::BLACK, Alignment::HORIZONTAL_RIGHT);

        $genByCol = $this->colLetter(max(2, $colCount - 1));
        $this->sheet->mergeCells("{$genByCol}7:{$lastCol}7");
        $this->sheet->setCellValue("{$genByCol}7", $generatedBy);
        $this->styleCell("{$genByCol}7", 10, false, self::BLACK);

        // Row 8: Empty
        $this->sheet->mergeCells("A8:{$lastCol}8");
    }

    //Add column headers at row 10
    private function addHeaders(array $headers, string $lastCol): void
    {
        $this->dataStartRow = 10;
        $headerRow = 9;

        foreach ($headers as $i => $header) {
            $col = $this->colLetter($i + 1);
            $this->sheet->setCellValue("{$col}{$headerRow}", $header);
        }

        // Style header row: red background, white bold text, borders
        $headerRange = "A{$headerRow}:{$lastCol}{$headerRow}";
        $this->sheet->getStyle($headerRange)->applyFromArray([
            'font' => [
                'bold' => true,
                'color' => ['argb' => self::WHITE],
                'size' => 11,
            ],
            'fill' => [
                'fillType' => Fill::FILL_SOLID,
                'startColor' => ['argb' => self::RED],
            ],
            'alignment' => [
                'horizontal' => Alignment::HORIZONTAL_CENTER,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['argb' => self::WHITE],
                ],
            ],
        ]);

        $this->sheet->getRowDimension($headerRow)->setRowHeight(28);
    }

    //Add data rows starting at row 11
    private function addData(array $data, int $colCount): void
    {
        $lastCol = $this->colLetter($colCount);

        foreach ($data as $rowIndex => $row) {
            $excelRow = $this->dataStartRow + $rowIndex;

            foreach (array_values($row) as $colIndex => $value) {
                $col = $this->colLetter($colIndex + 1);
                $this->sheet->setCellValue("{$col}{$excelRow}", $value);
            }

            // Plain data rows — no fill, no borders, just vertical alignment
            $rowRange = "A{$excelRow}:{$lastCol}{$excelRow}";
            $this->sheet->getStyle($rowRange)->applyFromArray([
                'alignment' => [
                    'vertical' => Alignment::VERTICAL_CENTER,
                ],
            ]);
        }
    }

    //Auto-size all columns
    private function autoSizeColumns(int $colCount): void
    {
        for ($i = 1; $i <= $colCount; $i++) {
            $col = $this->colLetter($i);
            $this->sheet->getColumnDimension($col)->setAutoSize(true);
        }
        // Minimum width for column A (logo space)
        $this->sheet->getColumnDimension('A')->setAutoSize(false);
        $this->sheet->getColumnDimension('A')->setWidth(14);
    }

    //Download the spreadsheet as a streamed response
    public function download(string $filename): StreamedResponse
    {
        $writer = new Xlsx($this->spreadsheet);

        return new StreamedResponse(function () use ($writer) {
            $writer->save('php://output');
        }, 200, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
            'Cache-Control' => 'max-age=0',
        ]);
    }

    //Convert 1-based column number to letter (1=A, 2=B, 27=AA, etc.)
    private function colLetter(int $num): string
    {
        $letter = '';
        while ($num > 0) {
            $num--;
            $letter = chr(65 + ($num % 26)) . $letter;
            $num = (int) ($num / 26);
        }
        return $letter;
    }

    //Style a cell
    private function styleCell(string $cell, int $size, bool $bold, string $color, string $align = Alignment::HORIZONTAL_LEFT): void
    {
        $this->sheet->getStyle($cell)->applyFromArray([
            'font' => [
                'bold' => $bold,
                'size' => $size,
                'color' => ['argb' => $color],
            ],
            'alignment' => [
                'horizontal' => $align,
                'vertical' => Alignment::VERTICAL_CENTER,
            ],
        ]);
    }
}
